# Generated by Django 5.2.3 on 2025-06-27 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(help_text="User's question (truncated if long)"),
                ),
                (
                    "response_length",
                    models.IntegerField(help_text="Length of AI response"),
                ),
                (
                    "context_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether knowledge base context was used",
                    ),
                ),
                (
                    "context_sources",
                    models.IntegerField(
                        default=0, help_text="Number of context sources used"
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(help_text="Response time in milliseconds"),
                ),
                (
                    "question_type",
                    models.CharField(
                        default="general",
                        help_text="Type of question (factual, analytical, procedural, opinion)",
                        max_length=50,
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="tinyllama",
                        help_text="AI model used for response",
                        max_length=50,
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        default="general",
                        help_text="Type of agent used (general, research, qa, content_analyzer)",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_usage_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="agent_usage_user_id_7b06f1_idx",
                    ),
                    models.Index(
                        fields=["agent_type", "timestamp"],
                        name="agent_usage_agent_t_0a1c67_idx",
                    ),
                    models.Index(
                        fields=["question_type", "timestamp"],
                        name="agent_usage_questio_938cab_idx",
                    ),
                ],
            },
        ),
    ]
