# Generated by Django 5.2.3 on 2025-06-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0002_remove_raw_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawljob",
            name="filter_type",
            field=models.CharField(
                default="pruning",
                help_text="Content filter type (pruning or bm25)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crawljob",
            name="use_content_filter",
            field=models.BooleanField(
                default=True, help_text="Use content filter for clean markdown"
            ),
        ),
    ]
