# Generated by Django 5.2.3 on 2025-06-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0003_crawljob_filter_type_crawljob_use_content_filter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crawljob",
            name="filter_type",
        ),
        migrations.RemoveField(
            model_name="crawljob",
            name="use_content_filter",
        ),
    ]
